export default [
  {
    id: 0,
    name: "Bethelhem S.",
    img:"https://media.istockphoto.com/id/1325565779/photo/smiling-african-american-business-woman-wearing-stylish-eyeglasses-looking-at-camera-standing.jpg?s=612x612&w=0&k=20&c=wsNA_POOFtsKGjucqci4ndeSX-NWcT3hEt9E3a_oXpY=" ,
    title: "CEO",
    email: "richard@gmail.com",
    par: " Bethelhem  has been with the company since its founding, and has a wealth of experience in the fashion industry. She is a visionary leader who is always looking for ways to take the company to the next level.",
  },
  {
    id: 1,
    img: "https://images.squarespace-cdn.com/content/v1/54c6eb0ce4b0f6cdd67c1196/1642223720668-I2XL35T6SMPTDZPOTRFJ/DCP_0085.jpg",
    name: "Beza K.",
    title: "COO",
    email: "Jared@gmail.com",
    par: "Beza brings a strong background in the fashion industry to the COO role, and has a track record of driving results and improving efficiency. ",
  },
  {
    id: 2,
    name: "Serjay P.",
    img:"https://media.istockphoto.com/id/1291318636/photo/put-more-in-get-more-out.jpg?s=170667a&w=0&k=20&c=DScVriJbWdYVLCkGAFd-gABvO5Why2eEG7SpGvl6LpA=",
    title: "Head of Marketing",
    email: "Dinesh@gmail.com",
    par: "Miki is a marketing expert with a talent for creating innovative campaigns that drive brand awareness and engagement.",
  },
  {
    id: 3,
    name: "Coleman Ohio",
    img:"https://media.istockphoto.com/id/1153206642/photo/confident-ginger-businessman-smiling-for-camera.jpg?s=612x612&w=0&k=20&c=xxN9v6-zB50n0_LW1Mi7ZiP5ilKH0Zh9sjI8G5S260c=",
    title: "Head of Product Development",
    email: "Gilfoyle@gmail.com",
    par: " Gilfoyle is responsible for leading the product development team, and is always on the lookout for new and exciting ideas.",
  },
  {
    id: 4,
    name: "Erlic Backman",
    img:"https://eyemediastudios.co.uk/wp-content/uploads/2021/02/photography-8.jpg",
    title: "Head of Customer Service ",
    email: "Erlick.B@gmail.com",
    par: "Erlice Backman is a customer service pro who is dedicated to ensuring that our customers have a positive experience every time they interact with us.",
  },
  {
    id: 5,
    name: "Monica Patrik",
    img:"https://thumbs.dreamstime.com/b/confident-business-asian-woman-isolated-studio-shot-portrait-professional-working-people-holding-tablet-computer-copy-183114166.jpg",
    title: "Head of Finance",
    email: "Monica@gmail.com",
    par: " Monica Patrik is a finance expert who plays a crucial role in ensuring the financial health of the company.",
  },
];
